### ISSUE TITLE
基于最新的jsdelivr条款的建议

### ISSUE THREAD

**Issue by philipsc** [892768447/flarum-ext-github-upload#10]
`https://github.com/jsdelivr/jsdelivr/issues/18229`
这个插件我相信在中国地区使用的比较多，所以大部分用户应该都使用了jsdelivr+github的方式，基于未来不可控因素，作者是否考虑在某个用户账号被禁的情况下支持开启本地上传功能，如果方便的话能支持拉取github文件到本地更好。

**Comment by 892768447** [comment]
emmm可以考虑加个开关，上传文件后不删除源文件
