### ISSUE TITLE
按钮样式

### ISSUE THREAD

**Issue by philipsc** [892768447/flarum-ext-github-upload#4]
不太喜欢编辑器上的按钮样式（鼠标移入后变成宽的动画效果）应该怎么让它变成静态的，而且图标我想换成fas fa-cloud-upload-alt，请问在哪里更换？

**Comment by 892768447** [comment]
图标：https://github.com/892768447/flarum-ext-github-upload/blob/master/js/src/forum/components/UploadButton.js#L28

**Comment by 892768447** [comment]
动画：https://github.com/892768447/flarum-ext-github-upload/blob/master/js/src/forum/index.js#L25

**Comment by philipsc** [comment]
修改后编辑器样式并没有改变 清除缓存也无效，好像调用的是vendor/irony/flarum-ext-github-upload/js/dist/forum.js这个文件中的样式，是要关闭插件再开启吗？

**Comment by 892768447** [comment]
嗯。关闭插件。重新开启。会重新打包生成新的首页js

**Comment by philipsc** [comment]
![批注 2020-07-29 185928](https://user-images.githubusercontent.com/31801469/88792361-b1d13480-d1cd-11ea-8312-0edac18a4e59.jpg)
我把这段悬停的代码注释了，并且也重启了插件，似乎不生效

**Comment by 892768447** [comment]
多刷新几次页面。检查页面的js， 搜索item-irony-github-upload。看看你注释的地方生效没

**Comment by philipsc** [comment]
检查了js，发现并未生效，包括修改的图标也未生效，禁用插件，php flarum cache:clear命令都试过了，浏览器缓存也清理过了

**Comment by 892768447** [comment]
这个我就不清楚了。我测试这样可以的。修改地方就是上面两个链接。剩下的你多尝试下怎么重新生成新的js

对了。可以去最后生成的那个js目录里。把原来的js删了，

**Comment by philipsc** [comment]
我检查发现似乎跟权限有关，因为composer安装的插件权限为root，但web权限是www，我改掉试试看

**Comment by philipsc** [comment]
不行，删掉dist/forum.js后不会自动生成文件，而且首页打开报错了

**Comment by 892768447** [comment]
![image](https://user-images.githubusercontent.com/5131669/88793954-4177e280-d1d0-11ea-87a3-b64ac5299fcb.png)

**Comment by philipsc** [comment]
这几个文件的时间是在变动的，但是irony/flarum-ext-github-upload/js/dist/forum.js 它一直没动

**Comment by philipsc** [comment]
我已经给了整个网站775权限，应该可以排除权限问题导致文件无法写入，是不是/js/dist/forum.js已经被写死了。

**Comment by 892768447** [comment]
进入js目录
webpack --mode production
