### ISSUE TITLE
希望可以增加状态显示

### ISSUE THREAD

**Issue by philipsc** [892768447/flarum-ext-github-upload#5]
文件上传的时候编辑框上传按钮图标希望增加一个loading状态。另外，当上传文件超过限制大小或限制类型时给出明确错误提示信息。

**Comment by 892768447** [comment]
已修复loading不显示问题，至于错误提示。失败后应该会在左下角有个红色的提示框，3秒消失

**Comment by philipsc** [comment]
还没发布正式版，升级命令是`composer require irony/flarum-ext-github-upload:dev-master`对吧

**Comment by 892768447** [comment]
嗯。先不慌。我测试下然后发布正式版

**Comment by philipsc** [comment]
> 嗯。先不慌。我测试下然后发布正式版

正式版能不能直接调整成一个正方形的小方块，像回帖预览的小眼睛哪种，比较简洁嘛

**Comment by philipsc** [comment]
图标用`fas fa-cloud-upload-alt`比较好看

**Comment by philipsc** [comment]
https://wedog.cc/ 已经配置并使用了，loading状态也能看到了，手机端效果也测试了。就是错误消息不显示内容，如下图
![批注 2020-07-30 175637](https://user-images.githubusercontent.com/31801469/88909737-10f67e00-d28e-11ea-8087-4e699b4faaad.jpg)

**Comment by 892768447** [comment]
> https://wedog.cc/ 已经配置并使用了，loading状态也能看到了，手机端效果也测试了。就是错误消息不显示内容，如下图
> ![批注 2020-07-30 175637](https://user-images.githubusercontent.com/31801469/88909737-10f67e00-d28e-11ea-8087-4e699b4faaad.jpg)

这个是做了什么操作导致的，上传什么文件？还是没配置后台

**Comment by philipsc** [comment]
> > https://wedog.cc/ 已经配置并使用了，loading状态也能看到了，手机端效果也测试了。就是错误消息不显示内容，如下图
> > ![批注 2020-07-30 175637](https://user-images.githubusercontent.com/31801469/88909737-10f67e00-d28e-11ea-8087-4e699b4faaad.jpg)
> 
> 这个是做了什么操作导致的，上传什么文件？还是没配置后台

上传一个大于限制大小的图片，我限制2M上传了3M（就为测试错误消息）
