### ISSUE TITLE
视频地址有问题

### ISSUE THREAD

**Issue by philipsc** [892768447/flarum-ext-github-upload#8]
![批注 2020-07-31 185224](https://user-images.githubusercontent.com/31801469/89028496-0d7ef780-d35f-11ea-8438-d0d067aa3c44.jpg)
刚刚升级到最新发布的版本了，发现上传后的视频并未采用Jsdelivr加速路径，导致国内无法播发的问题。

**Comment by philipsc** [comment]
不止视频，图片返回的路径也是github原始地址了

**Comment by philipsc** [comment]
![批注 2020-07-31 191327](https://user-images.githubusercontent.com/31801469/89029908-f097f380-d361-11ea-8e8f-f81174819697.jpg)
找到了，原来是插件增加了是否启用加速按钮，我没注意到

**Comment by philipsc** [comment]
感觉后续可以扩展支持腾讯COS，以此替代fof的上传插件，并且还可以增加一键将github附件转移到腾讯COS（以防加速失效后全站附件失效的尴尬）

**Comment by 892768447** [comment]
原来的fof上传好像有扩展可以支持七牛。
暂时没考虑扩展到国内的存储，毕竟要米，
暂时存github项目里，只要项目还在文件应该不会丢失

**Comment by philipsc** [comment]
> 原来的fof上传好像有扩展可以支持七牛。
> 暂时没考虑扩展到国内的存储，毕竟要米，
> 暂时存github项目里，只要项目还在文件应该不会丢失

前段时间不是传出Jsdelivr禁止空头访问嘛，一时间好多论坛都贴出403的截图，以为白嫖要凉凉了，心有余悸，考虑个最坏的打算吧，要是哪天Jsdelivr真的不支持大陆加速了，论坛附件在数据库有记录是不是可以通过一些方法拉回本地或者COS，让附件不至于罢工。虽然我在fof那边也提交了对接github的需求，但目前看来我不会使用那边的插件，因为他们的插件不兼容bbcode和markdown语法，如果插件卸载后所有附件都不能访问了，依赖性太强。
另外就是，刚刚更新了后发现错误消息依然没能显示！( ╯□╰ )

**Comment by 892768447** [comment]
附件都在github仓库里。就算不能用jsdelivr了。后台更新下数据库字段就可以切换github

错误消息还没弄完。看了下是抛出异常后结果走了框架的500错误了。看来还是直接用200返回文字算了

**Comment by philipsc** [comment]
> 附件都在github仓库里。就算不能用jsdelivr了。后台更新下数据库字段就可以切换github
> 
> 错误消息还没弄完。看了下是抛出异常后结果走了框架的500错误了。看来还是直接用200返回文字算了

切换github国内依然不能显示啊。。。

**Comment by philipsc** [comment]
> 附件都在github仓库里。就算不能用jsdelivr了。后台更新下数据库字段就可以切换github
> 
> 错误消息还没弄完。看了下是抛出异常后结果走了框架的500错误了。看来还是直接用200返回文字算了

开发辛苦了，可以考虑挂个打赏码，嘿嘿😊

**Comment by philipsc** [comment]
> 附件都在github仓库里。就算不能用jsdelivr了。后台更新下数据库字段就可以切换github
> 
> 错误消息还没弄完。看了下是抛出异常后结果走了框架的500错误了。看来还是直接用200返回文字算了

关于这个错误消息的通知，能不能在消息中看到详细信息，比如：
上文件为3196kb，限制2048kb。
文件类型为zip，非图片/视频文件。
