### ISSUE TITLE
Failed to fetch version info for philipsc/UP.

### ISSUE THREAD

**Issue by philipsc** [892768447/flarum-ext-github-upload#9]
是github限制上传了吗？今天所有的文件都是这个提示

**Comment by 892768447** [comment]
你是开了jsDeliver吧。这个东西也不是很稳，有时候需要一定的时间做缓存

**Comment by 892768447** [comment]
https://github.com/Inscryb/inscryb-markdown-editor/issues/1

**Comment by 892768447** [comment]
可能是jsDeliver的url有变动，最新提交的代码里把
/master/ 替换为了 @master/
/main/ 替换为了 @main/
